line-length = 100
target-version = "py39"

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # bugbear
    "UP",  # pyupgrade
    "C4",  # comprehensions
    "SIM", # simplify
]
ignore = [
    "E501",  # длину строк контролирует formatter
]

[lint.per-file-ignores]
"notebooks/*" = ["E402"]

[format]
quote-style = "double"
